export const cars = [
  {
    make: 'Volkswagen',
    model: 'Tiguan',
    year: 2019,
    mileage: 19855,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    price: 34888,
    img: {
      src: '/src/assets/images/volkswagen-tiguan.jpg',
      srcset:
        '/src/assets/images/volkswagen-tiguan.jpg 1x, /src/assets/images/volkswagen-tiguan-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Toyota',
    model: 'Highlander XLE',
    year: 2014,
    mileage: 69000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 27875,
    img: {
      src: '/src/assets/images/toyota-highlander-xle.jpg',
      srcset:
        '/src/assets/images/toyota-highlander-xle.jpg 1x, /src/assets/images/toyota-highlander-xle-2x.jpg 2x',
    },
    isNew: true,
    isSold: false,
  },
  {
    make: 'Lexus',
    model: 'RX 350 LUXURY',
    year: 2017,
    mileage: 39850,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 38775,
    img: {
      src: '/src/assets/images/lexus-rx-luxury.jpg',
      srcset:
        '/src/assets/images/lexus-rx-luxury.jpg 1x, /src/assets/images/lexus-rx-luxury-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Toyota',
    model: 'Highlander LE AWD',
    year: 2016,
    mileage: 104000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 23728,
    img: {
      src: '/src/assets/images/toyota-highlander-le.jpg',
      srcset:
        '/src/assets/images/toyota-highlander-le.jpg 1x, /src/assets/images/toyota-highlander-le-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Hyundai',
    model: 'Elantra',
    year: 2017,
    mileage: 95000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 11788,
    img: {
      src: '/src/assets/images/hyundai-elantra.jpg',
      srcset:
        '/src/assets/images/hyundai-elantra.jpg 1x, /src/assets/images/hyundai-elantra-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Mercedes-Benz',
    model: 'GLE-Class',
    year: 2016,
    mileage: 59800,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    price: 38878,
    img: {
      src: '/src/assets/images/mercedes-benz.jpg',
      srcset:
        '/src/assets/images/mercedes-benz.jpg 1x, /src/assets/images/mercedes-benz-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Toyota',
    model: 'Venza AWD XLE',
    year: 2015,
    mileage: 99000,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    price: 18620,
    img: {
      src: '/src/assets/images/toyota-venza.jpg',
      srcset:
        '/src/assets/images/toyota-venza.jpg 1x, /src/assets/images/toyota-venza-2x.jpg 2x',
    },
    isNew: false,
    isSold: true,
  },
  {
    make: 'Lexus',
    model: 'RX 350 F-SPORT',
    year: 2016,
    mileage: 86000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 34888,
    img: {
      src: '/src/assets/images/lexus-rx-fsport.jpg',
      srcset:
        '/src/assets/images/lexus-rx-fsport.jpg 1x, /src/assets/images/lexus-rx-fsport-2x.jpg 2x',
    },
    isNew: true,
    isSold: false,
  },
  {
    make: 'Volkswagen',
    model: 'Tiguan',
    year: 2019,
    mileage: 19855,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    price: 34888,
    img: {
      src: '/src/assets/images/volkswagen-tiguan.jpg',
      srcset:
        '/src/assets/images/volkswagen-tiguan.jpg 1x, /src/assets/images/volkswagen-tiguan-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Toyota',
    model: 'Highlander XLE',
    year: 2014,
    mileage: 69000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 27875,
    img: {
      src: '/src/assets/images/toyota-highlander-xle.jpg',
      srcset:
        '/src/assets/images/toyota-highlander-xle.jpg 1x, /src/assets/images/toyota-highlander-xle-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Lexus',
    model: 'RX 350 LUXURY',
    year: 2017,
    mileage: 39850,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 38775,
    img: {
      src: '/src/assets/images/lexus-rx-luxury.jpg',
      srcset:
        '/src/assets/images/lexus-rx-luxury.jpg 1x, /src/assets/images/lexus-rx-luxury-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Toyota',
    model: 'Highlander LE AWD',
    year: 2016,
    mileage: 104000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 23728,
    img: {
      src: '/src/assets/images/toyota-highlander-le.jpg',
      srcset:
        '/src/assets/images/toyota-highlander-le.jpg 1x, /src/assets/images/toyota-highlander-le-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Volkswagen',
    model: 'Tiguan',
    year: 2019,
    mileage: 19855,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    price: 34888,
    img: {
      src: '/src/assets/images/volkswagen-tiguan.jpg',
      srcset:
        '/src/assets/images/volkswagen-tiguan.jpg 1x, /src/assets/images/volkswagen-tiguan-2x.jpg 2x',
    },
    isNew: true,
    isSold: false,
  },
  {
    make: 'Toyota',
    model: 'Highlander XLE',
    year: 2014,
    mileage: 69000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 27875,
    img: {
      src: '/src/assets/images/toyota-highlander-xle.jpg',
      srcset:
        '/src/assets/images/toyota-highlander-xle.jpg 1x, /src/assets/images/toyota-highlander-xle-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Lexus',
    model: 'RX 350 LUXURY',
    year: 2017,
    mileage: 39850,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 38775,
    img: {
      src: '/src/assets/images/lexus-rx-luxury.jpg',
      srcset:
        '/src/assets/images/lexus-rx-luxury.jpg 1x, /src/assets/images/lexus-rx-luxury-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Toyota',
    model: 'Highlander LE AWD',
    year: 2016,
    mileage: 104000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 23728,
    img: {
      src: '/src/assets/images/toyota-highlander-le.jpg',
      srcset:
        '/src/assets/images/toyota-highlander-le.jpg 1x, /src/assets/images/toyota-highlander-le-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Hyundai',
    model: 'Elantra',
    year: 2017,
    mileage: 95000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 11788,
    img: {
      src: '/src/assets/images/hyundai-elantra.jpg',
      srcset:
        '/src/assets/images/hyundai-elantra.jpg 1x, /src/assets/images/hyundai-elantra-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Mercedes-Benz',
    model: 'GLE-Class',
    year: 2016,
    mileage: 59800,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    price: 38878,
    img: {
      src: '/src/assets/images/mercedes-benz.jpg',
      srcset:
        '/src/assets/images/mercedes-benz.jpg 1x, /src/assets/images/mercedes-benz-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Toyota',
    model: 'Venza AWD XLE',
    year: 2015,
    mileage: 99000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 18620,
    img: {
      src: '/src/assets/images/toyota-venza.jpg',
      srcset:
        '/src/assets/images/toyota-venza.jpg 1x, /src/assets/images/toyota-venza-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Lexus',
    model: 'RX 350 F-SPORT',
    year: 2016,
    mileage: 86000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 34888,
    img: {
      src: '/src/assets/images/lexus-rx-fsport.jpg',
      srcset:
        '/src/assets/images/lexus-rx-fsport.jpg 1x, /src/assets/images/lexus-rx-fsport-2x.jpg 2x',
    },
    isNew: true,
    isSold: false,
  },
  {
    make: 'Volkswagen',
    model: 'Tiguan',
    year: 2019,
    mileage: 19855,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    price: 34888,
    img: {
      src: '/src/assets/images/volkswagen-tiguan.jpg',
      srcset:
        '/src/assets/images/volkswagen-tiguan.jpg 1x, /src/assets/images/volkswagen-tiguan-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
  {
    make: 'Toyota',
    model: 'Highlander XLE',
    year: 2014,
    mileage: 69000,
    transmission: 'Automatic',
    fuelType: 'Gas',
    price: 27875,
    img: {
      src: '/src/assets/images/toyota-highlander-xle.jpg',
      srcset:
        '/src/assets/images/toyota-highlander-xle.jpg 1x, /src/assets/images/toyota-highlander-xle-2x.jpg 2x',
    },
    isNew: false,
    isSold: false,
  },
];
